version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: inventory-postgres
    restart: always
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventorypass1234
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
